apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80 # Expose as port 80 externally
      targetPort: 3000 # Internally forward to port 3000 of the container
  type: LoadBalancer # ClusterIP for local Kubernetes
