name: Lint Code

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
